export const GET_STATS_REQUEST = 'GET_STATS_REQUEST';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAILURE = 'GET_STATS_FAILURE';
export const GET_STATS_STREAM_START = 'GET_STATS_STREAM_START';
export const GET_STATS_STREAM_UPDATE = 'GET_STATS_STREAM_UPDATE';